version: '3.7'

services:
  rocrail:
    image: rocrail:0.0.1
    container_name: rocrail
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./config/rocrail:/root/Rocrail/default
    environment:
      - TZ=Europe/Zurich
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - default
    ports:
      - "8051:8051"
      - "8008:8008"
      - "8088:8088"
    depends_on:
      - "mqtt"

  mqtt:
    image: eclipse-mosquitto:2.0.14
    container_name: mqtt
    environment:
      - TZ=Europe/Zurich
    volumes:
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - default

  nodered:
    image: nodered/node-red
    container_name: nodered
    environment:
      - TZ=Europe/Zurich
    volumes:
      - ./config/nodered:/data
    networks:
      - default
    ports:
      - "1880:1880"
    depends_on:
      - "mqtt"
